<h1>Report PDF</h1>

<?php
$arrconf=array(PDF_UNIT, PDF_PAGE_FORMAT, PDF_CREATOR, PDF_HEADER_LOGO, PDF_HEADER_LOGO_WIDTH, PDF_HEADER_STRING, PDF_FONT_NAME_MAIN,  PDF_FONT_SIZE_MAIN, PDF_FONT_NAME_DATA, PDF_FONT_SIZE_DATA, PDF_MARGIN_HEADER, PDF_MARGIN_FOOTER, PDF_MARGIN_LEFT, PDF_MARGIN_TOP,  PDF_MARGIN_RIGHT, PDF_MARGIN_BOTTOM,K_PATH_IMAGES);
print_r($arrconf);
?>