<?php
$dataBanner = $this->m_invest->banner()->row();
$wh=array("status"=>"1");
$dataSlider = $this->m_invest->slider($wh);
$wh=array("status_approve !="=>"refuse");
$dataSumAllProduk = $this->m_invest->dataSumAllProduk($wh);
$danaTerkumpul = $this->m_invest->danaTerkumpul();
$keuntunganDibagikan = $this->m_invest->keuntunganDibagikan();
$wh = array("kategori"=>"perhatian","status_delete"=>"0");
$dataPerhatian = $this->m_invest->getPage($wh);
?>
<style>
	.dropdown-check-list{
    display: inline-block;
    width: 100%;
    }
    .dropdown-check-list:focus{
    outline:0;
    }
    .dropdown-check-list .anchor {
    width: 98%;
    position: relative;
    cursor: pointer;
    display: inline-block;
    padding-top:5px;
    padding-left:5px;
    padding-bottom:5px;
    border:1px #ccc solid;
    }
    .dropdown-check-list .anchor:after {
    position: absolute;
    content: "";
    border-left: 2px solid black;
    border-top: 2px solid black;
    padding: 5px;
    right: 10px;
    top: 20%;
    -moz-transform: rotate(-135deg);
    -ms-transform: rotate(-135deg);
    -o-transform: rotate(-135deg);
    -webkit-transform: rotate(-135deg);
    transform: rotate(-135deg);
    }
    .dropdown-check-list .anchor:active:after {
    right: 8px;
    top: 21%;
    }
    .dropdown-check-list ul.items {
    padding: 2px;
    display: none;
    margin: 0;
    border: 1px solid #ccc;
    border-top: none;
    }
    .dropdown-check-list ul.items li {
    list-style: none;
    }
    .dropdown-check-list.visible .anchor {
    color: #0094ff;
    }
    .dropdown-check-list.visible .items {
    display: block;
    }

    .carousel-control-prev-icon,
  .carousel-control-next-icon {
    height: 50px;
    width: 50px;
    border-radius: 50%;
    background-color: gray;
    background-size: 50%, 50%;
    transition:.2s;
  }

  .carousel-control-next-icon:hover
  {
    transform:scale(1.2);
      transition:.2s;
  }

  .carousel-control-prev-icon:hover {
    transform:scale(1.2);
      transition:.2s;
  }

  .carousel-indicators li {
    width: 10px;
    height: 10px;
    background-color: black;
    margin-left: 5px;
    margin-right: 5px;
    border-radius: 100%;
  }

  .carousel-indicators .active {
    margin-left: 5px;
    margin-right: 5px;
    background-color: green;
  }    


/**Styling scrollable elements*/

.js-scroll {
  opacity: 0;
  transition: opacity 500ms;
}
.js-scroll.scrolled {
  opacity: 1;
}
.scrolled.fade-in {
  animation: fade-in 1s ease-in-out both;
}
.scrolled.fade-in-bottom {
  animation: fade-in-bottom 1s ease-in-out both;
}
.scrolled.slide-left {
  animation: slide-in-left 1s ease-in-out both;
}
.scrolled.slide-right {
  animation: slide-in-right 1s ease-in-out both;
}

/* ----------------------------------------------
 * Generated by Animista on 2021-2-11 23:32:31
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

@keyframes slide-in-left {
  0% {
    -webkit-transform: translateX(-100px);
    transform: translateX(-100px);
    opacity: 0;
  }
  100% {
    -webkit-transform: translateX(0);
    transform: translateX(0);
    opacity: 1;
  }
}
@keyframes slide-in-right {
  0% {
    -webkit-transform: translateX(100px);
    transform: translateX(100px);
    opacity: 0;
  }
  100% {
    -webkit-transform: translateX(0);
    transform: translateX(0);
    opacity: 1;
  }
}
@keyframes fade-in-bottom {
  0% {
    -webkit-transform: translateY(50px);
    transform: translateY(50px);
    opacity: 0;
  }
  100% {
    -webkit-transform: translateY(0);
    transform: translateY(0);
    opacity: 1;
  }
}
@keyframes fade-in {
  0% {
    opacity: 0;
  }
  100% {
    opacity: 1;
  }
}
.h1, h1 {
    font-size: 24px !important;
}
.bg-light.border-0.shadow-lg {
	box-shadow: none !important;
}
section {
    padding: 3% 0%;
}
.form, .technology {
    background: #F9F9F9;
}
</style>
<script>
	
	$(window).scroll(function() {  

	var result1 = $("#textScroll").offset().top;
	var result2 = $("#formScroll").offset().top;
	var result20 = $(".img-scroll").offset().top;
	var result3 = $("#imgScroll").offset().top;
	var result4 = $("#detail").offset().top;
	var text1 = result1 - 700;
	var text2 = result2 - 700;
	var text3 = result3 - 700;
	var text20 = result20 - 700;
	var text4 = result4 - 400;
	    var scroll = $(window).scrollTop();
	    if (scroll >= text1) {
	        $(".text-scroll").addClass("scrolled");
	    }else{
	    	$(".text-scroll").removeClass("scrolled");
	    }
	    if (scroll >= text2) {
	        $(".text-scroll").addClass("scrolled");
	    }else{
	    	$(".text-scroll").removeClass("scrolled");
	    }
	    if (scroll >= text20) {
	        $(".img-scroll").addClass("scrolled");
	    }else{
	    	$(".img-scroll").removeClass("scrolled");
	    }
	    if (scroll >= text3) {
	        $("#imgScroll").addClass("scrolled");
	    }else{
	    	$("#imgScroll").removeClass("scrolled");
	    }
	    if (scroll >= text4) {
	        $("#detail").addClass("scrolled");
	    }else{
	    	$("#detail").removeClass("scrolled");
	    }
	});
jQuery(function ($) {
        var checkList = $('.dropdown-check-list');
        checkList.on('click', 'span.anchor', function(event){
            var element = $(this).parent();

            if ( element.hasClass('visible') )
            {
                element.removeClass('visible');
            }
            else
            {
                element.addClass('visible');
            }
        });
    });
</script>

<br><br>
<!--==========================
   Home Section style="background-color: rgb(214, 134, 44);"
============================-->
 
    		<!-- Slider -->
   <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
	  <ol class="carousel-indicators">
	  	<?php
		$nums=0;
		foreach($dataSlider->result() as $sl){
			?>
			<li data-target="#carouselExampleIndicators" data-slide-to="<?php echo $nums; ?>" class="<?php if($nums==0) echo 'active'; ?>"></li>
		<?php $nums++; } ?> 
	  </ol>
	  <div class="carousel-inner">
		<?php
		$nums=0;
		foreach($dataSlider->result() as $sl){
			?>
		<div class="carousel-item <?php if($nums ==0) echo "active";?>">
		  <img class="d-block w-100" src="<?php echo base_url() ?>/assets/img/slider/<?php echo $sl->image_slider; ?>"   alt="First slide">
		</div>
		<?php $nums++; } ?>
		 
	  </div>
	  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev" style="color: #C9FA98;">
		<span class="carousel-control-prev-icon" aria-hidden="true"></span>
		<span class="sr-only">Previous</span>
	  </a>
	  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
		<span class="carousel-control-next-icon" aria-hidden="true"></span>
		<span class="sr-only">Next</span>
	  </a>
	</div>
 
 
<section class="counter" id="team"  >
 
    <div class="container mt-5" >
 
		<div id="detail" class="row mb-5 scroll-element js-scroll fade-in-bottom">
			<?php
			if($dataSumAllProduk->num_rows()>0){
				$dts=$dataSumAllProduk->row();
				foreach($dataSumAllProduk->result() as $dts){
					$rp="";
					$jum=$dts->jum;
					if($dts->title=="Dana Terkumpul"){
						$rp="Rp ";
						$jum=$this->m_invest->terbilang($dts->jum);
					}
					$title= $dts->title;
					if($dts->title=="Proyek"){
						$title= "Total Usaha";
					}
					
					 
					?>
					<div class="col-md-3 text-center">
						<div class="row">
							<div class="col-md-12" >
								<h1><b class="<?php if($title=="Total Usaha") {echo "text-default";} else {echo "text-default";} ?>"><?php echo $rp.$jum; ?></b></h1>
								<p class="m-0 p-0"><?php echo strtoupper($title); ?></p>
							</div> 
						</div> 
					</div>
					<?php
				}
				$kumpul=0;
				foreach($danaTerkumpul->result() as $dtku){
					$kumpul=$kumpul+$dtku->jum;
				}
				$untung=0;
				foreach($keuntunganDibagikan->result() as $dtk){
					$untung=$untung+$dtk->jum;
				}
				?>
				<div class=" col-md-3 text-center">
					<div class="row">
						<div class="col-md-12" >
							<h1><b class="text-default">Rp <?php echo $this->m_invest->penyebut2($kumpul); ?></b></h1>
							<p class="m-0 p-0">TOTAL PENDANAAN</p>
						</div>
					</div>
				</div>
				<div class=" col-md-3 text-center ">
					<div class="row">
						<div class="col-md-12" >
							<h1><b class="text-default">Rp <?php echo $this->m_invest->penyebut2($untung); ?></b></h1>
							<p class="m-0 p-0">DEVIDEN DIBAGIKAN</p>
						</div>
					</div>
				</div>
				<?php
			}
			?>
		</div>
	</div>
</section>

<section class="form" id="team" class=""  >
 
    <div class="container mt-5" >
 
        <div  id="textScroll" class="row mt-5">
            <div class="col-md-12 text-scroll text-center scroll-element js-scroll fade-in-bottom">
                <h3><b>INVESTASI BISNIS YANG SEDANG BERLANGSUNG</b></h3>
				<p>Lihat daftar investasi bisnis yang sedang berlangsung dan temukan peluang untuk berinvestasi hari ini.</p>
				<br/>
				<br/>
            </div>
        </div>
		<form action="<?php echo base_url(); ?>" method="post">
			<div id="formScroll" class="row mb-5 text-scroll scroll-element js-scroll fade-in-bottom">
				<div class="col-md-3">
					<!--<h6>Tipe Kampanye <i class="fa fa-chevron-down"></i></h6>-->
					<div id="list3" class="dropdown-check-list">
						<span class="anchor">Tipe Bisnis </span>
						<ul class="items">
							<li><table width="100%"><tr>
								<td width="15%"><input class="rf" name="kampanye" type="radio" value="all" checked /></td>
								<td>Lihat Semua</td>
								</tr>
								</table>
							</li>
							
						</ul>
					</div>
				</div>
				<div class="col-md-3">
					<!--<h6>Lama Tenor <i class="fa fa-chevron-down"></i></h6>-->
					<div id="list3" class="dropdown-check-list">
						<span class="anchor">Waktu Pembagian</span>
						<ul class="items">
							<li><table width="100%"><tr>
								<td width="15%"><input class="rf" name="tenor" type="radio" value="all" checked /></td>
								<td>Lihat Semua</td>
								</tr>
								</table>
							</li>
							<li><table width="100%"><tr>
								<td width="15%"><input class="rf" name="tenor" type="radio" value="lt6"/></td>
								<td><= 1 Bulan</td>
								</tr>
								</table>
							</li>
							<li><table width="100%"><tr>
								<td width="15%"><input class="rf" name="tenor" type="radio" value="gt6"/></td>
								<td>> 1 Bulan</td>
								</tr>
								</table>
							</li>
						</ul>
					</div>
				</div>
				
				<div class="col-md-3">
					<!--<h6>Bunga Efektif <i class="fa fa-chevron-down"></i></h6>-->
					<div id="list3" class="dropdown-check-list">
						<span class="anchor">Pembagian Dividen</span>
						<ul class="items">
							<li><table width="100%"><tr>
								<td width="15%"><input class="rf" name="bunga" type="radio" value="all" checked /></td>
								<td>Lihat Semua</td>
								</tr>
								</table>
							</li>
							<li><table width="100%"><tr>
								<td width="15%"><input class="rf" name="bunga" type="radio" value="lt12"/></td>
								<td><= 50%</td>
								</tr>
								</table>
							</li>
							<li><table width="100%"><tr>
								<td width="15%"><input class="rf" name="bunga" type="radio" value="gt12"/></td>
								<td>> 50%</td>
								</tr>
								</table>
							</li>
							 
						</ul>
					</div>
				</div>
				  
				
				<div class="col-md-3">
					<!--<h6>Urutan <i class="fa fa-chevron-down"></i></h6>-->
					<div id="list3" class="dropdown-check-list">
						<span class="anchor">Urutan </span>
						<ul class="items">
							<li><table width="100%"><tr>
								<td width="15%"><input class="rf" name="urutan" type="radio" value="all" checked /></td>
								<td>Lihat Semua</td>
								</tr>
								</table>
							</li>
							<li><table width="100%"><tr>
								<td width="15%"><input class="rf" name="urutan" type="radio" value="Oldest"/></td>
								<td>Bisnis Terlama</td>
								</tr>
								</table>
							</li>
							<li><table width="100%"><tr>
								<td width="15%"><input class="rf" name="urutan" type="radio" value="Newest"/></td>
								<td>Bisnis Terbaru</td>
								</tr>
								</table>
							</li>
							<li><table width="100%"><tr>
								<td width="15%"><input class="rf" name="urutan" type="radio" value="Smallest"/></td>
								<td>Nilai Terkecil</td>
								</tr>
								</table>
							</li>
							<li><table width="100%"><tr>
								<td width="15%"><input class="rf" name="urutan" type="radio" value="Biggest"/></td>
								<td>Nilai Terbesar</td>
								</tr>
								</table>
							</li>
							<li><table width="100%"><tr>
								<td width="15%"><input class="rf" name="urutan" type="radio" value="smallrose"/></td>
								<td>Dividen Terkecil</td>
								</tr>
								</table>
							</li>
							<li><table width="100%"><tr>
								<td width="15%"><input class="rf" name="urutan" type="radio" value="bigrose"/></td>
								<td>Dividen Terbesar</td>
								</tr>
								</table>
							</li>
						</ul>
					</div>
				</div>
			</div>
		</form>
	<!--
		Sample <a href="https://web.whatsapp.com/send?phone=+6289699935552&amp;text=Salam Kenal Mas Nuris, Saya Ingin Diskusi" onclick="gtag('event', 'WhatsApp', {'event_action': 'whatsapp_chat', 'event_category': 'Chat', 'event_label': 'Chat_WhatsApp'});" target="_blank">Konsultasi Via Whatapps</a>
		-->
		<br><br>

	</div> <!-- div produk -->
</section>
<section class="product" id="product">
	<div class="container mt-5">
		<div class="row mt-3 img-scroll scroll-element js-scroll fade-in-bottom" id="list-data">
            <?php
			$datany['data_produk']=$data_produk;
            $this->load->view("list-data",$datany);
            
            ?>
        </div>
	</div>
</section>
<section class="technology" >
	<div class="container mt-5">
		<div id="imgScroll" class="container mt-5 scroll-element js-scroll fade-in-bottom" >
	        <div class="row mt-5">
	            <div class="col-md-6">
					<?php
					$ext = $this->m_invest->get_file_extension($dataBanner->image_banner);
					if($ext=="svg"){
					?>
	                <embed name="E" id="E" src="<?php echo base_url() ?>assets/img/banner/<?php echo $dataBanner->image_banner; ?>" width="100%">
					<?php
					} else {
					?>
					<img src="<?php echo base_url() ?>assets/img/banner/<?php echo $dataBanner->image_banner; ?>" width="100%" />
					<?php
					}
					?>
	            </div>
	            <div class="col-md-6">
	                <h3><?php echo $dataBanner->title_banner; ?></h3>
	                <p><?php echo $dataBanner->desc_banner; ?></p>
	            </div>
	        </div>
	    </div>
    </div>
</section><!-- #team -->
<?php

?>
<script type="text/javascript">
	if(sessionStorage.getItem("partner_tx_id")){
		if(sessionStorage.getItem("partner_tx_id") != ''){
        	var trx = sessionStorage.getItem("partner_tx_id");
        	var settings = {
			  "url": "https://api-stg.oyindonesia.com/api/payment-checkout/status?partner_tx_id="+trx+"&send_callback=false",
			  "method": "GET",
			  "timeout": 0,
			  "headers": {
			    "x-oy-username": "pendanaid",
			    "x-api-key": "d4223670-1abb-491c-be03-c32370774324",
			    "content-type": "application/json"
			  },
			};

			$.ajax(settings).done(function (response) {
			  console.log(response);
			  // sessionStorage.setItem("partner_tx_id", "");
			  data = {
		        amount:response.data.amount,
		        sender_name:response.data.sender_name,
		        status:response.data.status,
		        email:response.data.email,
		      }
		      console.log(data);
		      if(response.data.status=="complete"){
		      $.ajax({
			      method: "POST",
			      url: "<?php echo base_url('investor/saveOy'); ?>",
			      data: data 
			      
			    })
		      	sessionStorage.setItem("partner_tx_id", "");
		  		}else{
		  			console.log('not set yet');
		  		}
			});
    	}
    }

	$(document).ready(function(){
		$(".rf").change(function(){
			filternya();
		});
	});
	function filternya(){ 
		var n=0;
		var nilai = {};
		var fi=["kampanye","tenor","bunga","urutan"];
		$(".rf:checked").each(function(){
			var tv = $(this).val();
			nilai[fi[n]]=tv;
			//console.log("val"+n+"->"+tv);
			n++;
		});
		console.log(nilai);
		$.ajax({
			url: "<?php echo base_url(); ?>invest/indexfilter", 
			data : nilai,
			type:"post",
			dataType:"html",
			success: function(result){ 
				$("#list-data").html(result);
			}
		});
	}
</script>