<?php
$dataBanner = $this->m_invest->banner()->row();
$wh=array("status"=>"1");
$dataSlider = $this->m_invest->slider($wh);
$wh=array("status_approve !="=>"refuse");
$dataSumAllProduk = $this->m_invest->dataSumAllProduk($wh);
$danaTerkumpul = $this->m_invest->danaTerkumpul();
$keuntunganDibagikan = $this->m_invest->keuntunganDibagikan();
$wh = array("kategori"=>"perhatian","status_delete"=>"0");
$dataPerhatian = $this->m_invest->getPage($wh);
?>
<style>
    .dropdown-check-list{
    display: inline-block;
    width: 100%;
    }
    .dropdown-check-list:focus{
    outline:0;
    }
    .dropdown-check-list .anchor {
    width: 98%;
    position: relative;
    cursor: pointer;
    display: inline-block;
    padding-top:5px;
    padding-left:5px;
    padding-bottom:5px;
    border:1px #ccc solid;
    }
    .dropdown-check-list .anchor:after {
    position: absolute;
    content: "";
    border-left: 2px solid black;
    border-top: 2px solid black;
    padding: 5px;
    right: 10px;
    top: 20%;
    -moz-transform: rotate(-135deg);
    -ms-transform: rotate(-135deg);
    -o-transform: rotate(-135deg);
    -webkit-transform: rotate(-135deg);
    transform: rotate(-135deg);
    }
    .dropdown-check-list .anchor:active:after {
    right: 8px;
    top: 21%;
    }
    .dropdown-check-list ul.items {
    padding: 2px;
    display: none;
    margin: 0;
    border: 1px solid #ccc;
    border-top: none;
    }
    .dropdown-check-list ul.items li {
    list-style: none;
    }
    .dropdown-check-list.visible .anchor {
    color: #0094ff;
    }
    .dropdown-check-list.visible .items {
    display: block;
    }
/**Styling scrollable elements*/

.js-scroll {
  opacity: 0;
  transition: opacity 500ms;
}
.js-scroll.scrolled {
  opacity: 1;
}
.scrolled.fade-in {
  animation: fade-in 1s ease-in-out both;
}
.scrolled.fade-in-bottom {
  animation: fade-in-bottom 1s ease-in-out both;
}
.scrolled.slide-left {
  animation: slide-in-left 1s ease-in-out both;
}
.scrolled.slide-right {
  animation: slide-in-right 1s ease-in-out both;
}

/* ----------------------------------------------
 * Generated by Animista on 2021-2-11 23:32:31
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

@keyframes slide-in-left {
  0% {
    -webkit-transform: translateX(-100px);
    transform: translateX(-100px);
    opacity: 0;
  }
  100% {
    -webkit-transform: translateX(0);
    transform: translateX(0);
    opacity: 1;
  }
}
@keyframes slide-in-right {
  0% {
    -webkit-transform: translateX(100px);
    transform: translateX(100px);
    opacity: 0;
  }
  100% {
    -webkit-transform: translateX(0);
    transform: translateX(0);
    opacity: 1;
  }
}
@keyframes fade-in-bottom {
  0% {
    -webkit-transform: translateY(50px);
    transform: translateY(50px);
    opacity: 0;
  }
  100% {
    -webkit-transform: translateY(0);
    transform: translateY(0);
    opacity: 1;
  }
}
@keyframes fade-in {
  0% {
    opacity: 0;
  }
  100% {
    opacity: 1;
  }
}
.h1, h1 {
    font-size: 24px !important;
}
.bg-light.border-0.shadow-lg {
	box-shadow: none !important;
}
section {
    padding: 3% 0%;
}
.forns, .technology {
    background: #F9F9F9;
}
</style>
<script>
	
	$(window).scroll(function() {	
	var result1 = $("#textScroll").offset().top;
	var result3 = $("#imgScroll").offset().top;
	var text1 = result1 - 500;
	var text3 = result3 - 500;
	    var scroll = $(window).scrollTop();
	    if (scroll >= text1) {
	        $("#textScroll").addClass("scrolled");
	    }else{
	    	$("#textScroll").removeClass("scrolled");
	    }
	    if (scroll >= text3) {
	        $("#imgScroll").addClass("scrolled");
	    }else{
	    	$("#imgScroll").removeClass("scrolled");
	    }
	});
	$(document).ready(function(){
		var result1 = $("#textScroll").offset().top;
		var text1 = result1 - 500;
		var scroll = $(window).scrollTop();
	    if (scroll >= text1) {
	        $("#textScroll").addClass("scrolled");
	    }else{
	    	$("#textScroll").removeClass("scrolled");
	    }
	});
jQuery(function ($) {
        var checkList = $('.dropdown-check-list');
        checkList.on('click', 'span.anchor', function(event){
            var element = $(this).parent();

            if ( element.hasClass('visible') )
            {
                element.removeClass('visible');
            }
            else
            {
                element.addClass('visible');
            }
        });
    });
</script>

<br><br><br> 

<section class="forns" id="team"  >
 
    <div id="textScroll" class="container mt-1 scroll-element js-scroll fade-in-bottom" >
 
        <div class="row mt-5">
            <div class="col-md-12 text-center">
                <h3><b>INVESTASI BISNIS SEKUNDER</b></h3>
				<p>Lihat daftar investasi bisnis yang sedang berlangsung dan temukan peluang untuk berinvestasi hari ini.</p>
            </div>
        </div>
		<form class="form" action="<?php echo base_url(); ?>" method="post">
			<div class="row mb-5">
				<div class="col-md-3">
					<!--<h6>Tipe Kampanye <i class="fa fa-chevron-down"></i></h6>-->
					<div id="list3" class="dropdown-check-list">
						<span class="anchor">Tipe Bisnis </span>
						<ul class="items">
							<li><table width="100%"><tr>
								<td width="15%"><input class="rf" name="kampanye" type="radio" value="all" checked /></td>
								<td>Lihat Semua</td>
								</tr>
								</table>
							</li>
							
						</ul>
					</div>
				</div>
				<div class="col-md-3">
					<!--<h6>Lama Tenor <i class="fa fa-chevron-down"></i></h6>-->
					<div id="list3" class="dropdown-check-list">
						<span class="anchor">Waktu Pembagian</span>
						<ul class="items">
							<li><table width="100%"><tr>
								<td width="15%"><input class="rf" name="tenor" type="radio" value="all" checked /></td>
								<td>Lihat Semua</td>
								</tr>
								</table>
							</li>
							<li><table width="100%"><tr>
								<td width="15%"><input class="rf" name="tenor" type="radio" value="lt6"/></td>
								<td><= 1 Bulan</td>
								</tr>
								</table>
							</li>
							<li><table width="100%"><tr>
								<td width="15%"><input class="rf" name="tenor" type="radio" value="gt6"/></td>
								<td>> 1 Bulan</td>
								</tr>
								</table>
							</li>
						</ul>
					</div>
				</div>
				
				<div class="col-md-3">
					<!--<h6>Bunga Efektif <i class="fa fa-chevron-down"></i></h6>-->
					<div id="list3" class="dropdown-check-list">
						<span class="anchor">Pembagian Dividen</span>
						<ul class="items">
							<li><table width="100%"><tr>
								<td width="15%"><input class="rf" name="bunga" type="radio" value="all" checked /></td>
								<td>Lihat Semua</td>
								</tr>
								</table>
							</li>
							<li><table width="100%"><tr>
								<td width="15%"><input class="rf" name="bunga" type="radio" value="lt12"/></td>
								<td><= 50%</td>
								</tr>
								</table>
							</li>
							<li><table width="100%"><tr>
								<td width="15%"><input class="rf" name="bunga" type="radio" value="gt12"/></td>
								<td>> 50%</td>
								</tr>
								</table>
							</li>
							 
						</ul>
					</div>
				</div>
				  
				
				<div class="col-md-3">
					<!--<h6>Urutan <i class="fa fa-chevron-down"></i></h6>-->
					<div id="list3" class="dropdown-check-list">
						<span class="anchor">Urutan </span>
						<ul class="items">
							<li><table width="100%"><tr>
								<td width="15%"><input class="rf" name="urutan" type="radio" value="all" checked /></td>
								<td>Lihat Semua</td>
								</tr>
								</table>
							</li>
							<li><table width="100%"><tr>
								<td width="15%"><input class="rf" name="urutan" type="radio" value="Oldest"/></td>
								<td>Bisnis Terlama</td>
								</tr>
								</table>
							</li>
							<li><table width="100%"><tr>
								<td width="15%"><input class="rf" name="urutan" type="radio" value="Newest"/></td>
								<td>Bisnis Terbaru</td>
								</tr>
								</table>
							</li>
							<li><table width="100%"><tr>
								<td width="15%"><input class="rf" name="urutan" type="radio" value="Smallest"/></td>
								<td>Nilai Terkecil</td>
								</tr>
								</table>
							</li>
							<li><table width="100%"><tr>
								<td width="15%"><input class="rf" name="urutan" type="radio" value="Biggest"/></td>
								<td>Nilai Terbesar</td>
								</tr>
								</table>
							</li>
							<li><table width="100%"><tr>
								<td width="15%"><input class="rf" name="urutan" type="radio" value="smallrose"/></td>
								<td>Dividen Terkecil</td>
								</tr>
								</table>
							</li>
							<li><table width="100%"><tr>
								<td width="15%"><input class="rf" name="urutan" type="radio" value="bigrose"/></td>
								<td>Dividen Terbesar</td>
								</tr>
								</table>
							</li>
						</ul>
					</div>
				</div>
			</div>
		</form>
	</div>
</section>
<section class="product" id="product">
	<div class="container mt-5">

        <div class="row mt-3 img-scroll" id="list-data">
            <?php
			$datany['data_produk']=$data_produk;
            $this->load->view("list-data-sekunder",$datany);
            
            ?>
        </div>
	</div>
</section>

<section class="technology" >
	<div class="container mt-5">
        <div id="imgScroll" class="container mt-5 scroll-element js-scroll fade-in-bottom" >
            <div class="col-md-6">
				<?php
				$ext = $this->m_invest->get_file_extension($dataBanner->image_banner);
				if($ext=="svg"){
				?>
                <embed name="E" id="E" src="<?php echo base_url() ?>assets/img/banner/<?php echo $dataBanner->image_banner; ?>" width="100%">
				<?php
				} else {
				?>
				<img src="<?php echo base_url() ?>assets/img/banner/<?php echo $dataBanner->image_banner; ?>" width="100%" />
				<?php
				}
				?>
            </div>
            <div class="col-md-6">
                <h3><?php echo $dataBanner->title_banner; ?></h3>
                <p><?php echo $dataBanner->desc_banner; ?></p>
            </div>
        </div>
    </div>
</section><!-- #team -->
<?php

?>
<script>
	$(document).ready(function(){
		$(".rf").change(function(){
			filternya();
		});
	});
	function filternya(){ 
		var n=0;
		var nilai = {};
		var fi=["kampanye","tenor","bunga","urutan"];
		$(".rf:checked").each(function(){
			var tv = $(this).val();
			nilai[fi[n]]=tv;
			//console.log("val"+n+"->"+tv);
			n++;
		});
		console.log(nilai);
		$.ajax({
			url: "<?php echo base_url(); ?>invest/indexfilterSekunder", 
			data : nilai,
			type:"post",
			dataType:"html",
			success: function(result){ 
				$("#list-data").html(result);
			}
		});
	}
</script>