<?php
$dataBanner = $this->m_invest->banner()->row();
$wh=array("status"=>"1");
$dataSlider = $this->m_invest->slider($wh);
$wh=array("status_approve !="=>"refuse");
$dataSumAllProduk = $this->m_invest->dataSumAllProduk($wh);
$danaTerkumpul = $this->m_invest->danaTerkumpul();
$keuntunganDibagikan = $this->m_invest->keuntunganDibagikan();
$wh = array("kategori"=>"perhatian","status_delete"=>"0");
$dataPerhatian = $this->m_invest->getPage($wh);
?>
<style>
	.dropdown-check-list{
    display: inline-block;
    width: 100%;
    }
    .dropdown-check-list:focus{
    outline:0;
    }
    .dropdown-check-list .anchor {
    width: 98%;
    position: relative;
    cursor: pointer;
    display: inline-block;
    padding-top:5px;
    padding-left:5px;
    padding-bottom:5px;
    border:1px #ccc solid;
    }
    .dropdown-check-list .anchor:after {
    position: absolute;
    content: "";
    border-left: 2px solid black;
    border-top: 2px solid black;
    padding: 5px;
    right: 10px;
    top: 20%;
    -moz-transform: rotate(-135deg);
    -ms-transform: rotate(-135deg);
    -o-transform: rotate(-135deg);
    -webkit-transform: rotate(-135deg);
    transform: rotate(-135deg);
    }
    .dropdown-check-list .anchor:active:after {
    right: 8px;
    top: 21%;
    }
    .dropdown-check-list ul.items {
    padding: 2px;
    display: none;
    margin: 0;
    border: 1px solid #ccc;
    border-top: none;
    }
    .dropdown-check-list ul.items li {
    list-style: none;
    }
    .dropdown-check-list.visible .anchor {
    color: #0094ff;
    }
    .dropdown-check-list.visible .items {
    display: block;
    }

    .carousel-control-prev-icon,
  .carousel-control-next-icon {
    height: 50px;
    width: 50px;
    border-radius: 50%;
    background-color: gray;
    background-size: 50%, 50%;
    transition:.2s;
  }

  .carousel-control-next-icon:hover
  {
    transform:scale(1.2);
      transition:.2s;
  }

  .carousel-control-prev-icon:hover {
    transform:scale(1.2);
      transition:.2s;
  }

  .carousel-indicators li {
    width: 10px;
    height: 10px;
    background-color: black;
    margin-left: 5px;
    margin-right: 5px;
    border-radius: 100%;
  }

  .carousel-indicators .active {
    margin-left: 5px;
    margin-right: 5px;
    background-color: green;
  }    


/**Styling scrollable elements*/

.js-scroll {
  opacity: 0;
  transition: opacity 500ms;
}
.js-scroll.scrolled {
  opacity: 1;
}
.scrolled.fade-in {
  animation: fade-in 1s ease-in-out both;
}
.scrolled.fade-in-bottom {
  animation: fade-in-bottom 1s ease-in-out both;
}
.scrolled.slide-left {
  animation: slide-in-left 1s ease-in-out both;
}
.scrolled.slide-right {
  animation: slide-in-right 1s ease-in-out both;
}

/* ----------------------------------------------
 * Generated by Animista on 2021-2-11 23:32:31
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

@keyframes slide-in-left {
  0% {
    -webkit-transform: translateX(-100px);
    transform: translateX(-100px);
    opacity: 0;
  }
  100% {
    -webkit-transform: translateX(0);
    transform: translateX(0);
    opacity: 1;
  }
}
@keyframes slide-in-right {
  0% {
    -webkit-transform: translateX(100px);
    transform: translateX(100px);
    opacity: 0;
  }
  100% {
    -webkit-transform: translateX(0);
    transform: translateX(0);
    opacity: 1;
  }
}
@keyframes fade-in-bottom {
  0% {
    -webkit-transform: translateY(50px);
    transform: translateY(50px);
    opacity: 0;
  }
  100% {
    -webkit-transform: translateY(0);
    transform: translateY(0);
    opacity: 1;
  }
}
@keyframes fade-in {
  0% {
    opacity: 0;
  }
  100% {
    opacity: 1;
  }
}
.h1, h1 {
    font-size: 24px !important;
}
.bg-light.border-0.shadow-lg {
	box-shadow: none !important;
}
section {
    padding: 3% 0%;
}
.form, .technology {
    background: #F9F9F9;
}
</style>
<script>
	
	$(window).scroll(function() {  

	var result1 = $("#textScroll").offset().top;
	var result2 = $("#formScroll").offset().top;
	var result20 = $(".img-scroll").offset().top;
	var result3 = $("#imgScroll").offset().top;
	var result4 = $("#detail").offset().top;
	var text1 = result1 - 700;
	var text2 = result2 - 700;
	var text3 = result3 - 700;
	var text20 = result20 - 700;
	var text4 = result4 - 400;
	    var scroll = $(window).scrollTop();
	    if (scroll >= text1) {
	        $(".text-scroll").addClass("scrolled");
	    }else{
	    	$(".text-scroll").removeClass("scrolled");
	    }
	    if (scroll >= text2) {
	        $(".text-scroll").addClass("scrolled");
	    }else{
	    	$(".text-scroll").removeClass("scrolled");
	    }
	    if (scroll >= text20) {
	        $(".img-scroll").addClass("scrolled");
	    }else{
	    	$(".img-scroll").removeClass("scrolled");
	    }
	    if (scroll >= text3) {
	        $("#imgScroll").addClass("scrolled");
	    }else{
	    	$("#imgScroll").removeClass("scrolled");
	    }
	    if (scroll >= text4) {
	        $("#detail").addClass("scrolled");
	    }else{
	    	$("#detail").removeClass("scrolled");
	    }
	});
jQuery(function ($) {
        var checkList = $('.dropdown-check-list');
        checkList.on('click', 'span.anchor', function(event){
            var element = $(this).parent();

            if ( element.hasClass('visible') )
            {
                element.removeClass('visible');
            }
            else
            {
                element.addClass('visible');
            }
        });
    });
</script>

<section class="hero">
	<div class="container">
		<div class="row position-relative">
			<div class="col-md-6 my-auto">
				<h1 class="headline mb-4" data-aos="fade-up" data-aos-once="true"
					data-aos-duration="600">Securities
					Crowdfunding Yang
					<span class="text-blue">Profitable</span>
				</h1>
				<p class="sub-headline" data-aos="fade-up" data-aos-once="true"
					data-aos-delay="300" data-aos-duration="600">Bursa Efek UMKM dan UMK yang aman, halal,
					berjaminan dan menguntungkan</p>

				<div class="row headline-points">
					<div class="col-md-6" data-aos="fade-up" data-aos-once="true" data-aos-delay="600"
						data-aos-duration="600"><img src="<?= base_url(); ?>assets/img/new/check.png" alt="vector"
							class="mr-3">Berizin Dan
						Diawasi OJK</div>
					<div class="col-md-6" data-aos="fade-up" data-aos-once="true" data-aos-delay="900"
						data-aos-duration="600"><img src="<?= base_url(); ?>assets/img/new/check.png" alt="vector"
							class="mr-3">Mudah</div>
					<div class="col-md-6" data-aos="fade-up" data-aos-once="true" data-aos-delay="1200"
						data-aos-duration="600"><img src="<?= base_url(); ?>assets/img/new/check.png" alt="vector"
							class="mr-3">100%
						Transparan</div>
					<div class="col-md-6" data-aos="fade-up" data-aos-once="true" data-aos-delay="1500"
						data-aos-duration="600"><img src="<?= base_url(); ?>assets/img/new/check.png" alt="vector"
							class="mr-3">Lebih Dari
						180+ Project</div>
				</div>
			</div>
			<div class="col-md-6 form-register mt-5 mt-md-0">
				<div class="card ml-auto" data-aos="fade-left" data-aos-once="true" data-aos-delay="1800"
					data-aos-duration="600">
					<form action="">
						<div class="input-group mb-4">
							<label for="email" class="w-100">Email</label>
							<input type="email" id="email" class="form-control mt-2"
								placeholder="Example@example.com">
						</div>
						<div class="input-group mb-4">
							<label for="password" class="w-100">Password</label>
							<input type="password" id="password" class="form-control mt-2"
								placeholder="Example@example.com">
						</div>
						<div class="input-group mb-4">
							<label for="re_password" class="w-100">Repeat Password</label>
							<input type="re_password" id="re_password" class="form-control mt-2"
								placeholder="Example@example.com">
						</div>

						<button type="submit" class="btn btn-block btn-blue">Get Started</button>

						<div class="row mt-4 license mx-0">
							<div class="col-1 px-0"><img
									src="https://api.elements.buildwithangga.com/storage/files/2/assets/Header/HeaderFinance-1/award.png"
									alt="award" class="img-fluid"></div>
							<div class="col-11">Licensed and regulated by The Monetary
								Authority of Singapore, Hong Kong Customs and Excise Department and Bank Indonesia.
							</div>
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>
</section>
<!-- <section class="counter" id="team"  >
 
    <div class="container mt-5" >
 
		<div id="detail" class="row mb-5 scroll-element js-scroll fade-in-bottom">
			<?php
			if($dataSumAllProduk->num_rows()>0){
				$dts=$dataSumAllProduk->row();
				foreach($dataSumAllProduk->result() as $dts){
					$rp="";
					$jum=$dts->jum;
					if($dts->title=="Dana Terkumpul"){
						$rp="Rp ";
						$jum=$this->m_invest->terbilang($dts->jum);
					}
					$title= $dts->title;
					if($dts->title=="Proyek"){
						$title= "Total Usaha";
					}
					
					 
					?>
					<div class="col-md-3 text-center">
						<div class="row">
							<div class="col-md-12" >
								<h1><b class="<?php if($title=="Total Usaha") {echo "text-default";} else {echo "text-default";} ?>"><?php echo $rp.$jum; ?></b></h1>
								<p class="m-0 p-0"><?php echo strtoupper($title); ?></p>
							</div> 
						</div> 
					</div>
					<?php
				}
				$kumpul=0;
				foreach($danaTerkumpul->result() as $dtku){
					$kumpul=$kumpul+$dtku->jum;
				}
				$untung=0;
				foreach($keuntunganDibagikan->result() as $dtk){
					$untung=$untung+$dtk->jum;
				}
				?>
				<div class=" col-md-3 text-center">
					<div class="row">
						<div class="col-md-12" >
							<h1><b class="text-default">Rp <?php echo $this->m_invest->penyebut2($kumpul); ?></b></h1>
							<p class="m-0 p-0">TOTAL PENDANAAN</p>
						</div>
					</div>
				</div>
				<div class=" col-md-3 text-center ">
					<div class="row">
						<div class="col-md-12" >
							<h1><b class="text-default">Rp <?php echo $this->m_invest->penyebut2($untung); ?></b></h1>
							<p class="m-0 p-0">DEVIDEN DIBAGIKAN</p>
						</div>
					</div>
				</div>
				<?php
			}
			?>
		</div>
	</div>
</section> -->

<section class="benefit">
	<div class="container">
		<h2 class="text-center" data-aos="fade-up" data-aos-once="true"
			data-aos-duration="600">Keunggulan Investasi Dengan Kami</h2>
		<p class="text-center text-grey" data-aos="fade-up" data-aos-once="true"
			data-aos-delay="300" data-aos-duration="600">Lorem ipsum dolor sit amet consectetur adipisicing
			elit. Ipsam, cum?
		</p>
		<div class="row benefit-list py-5">
			<div class="col-12 col-md-6 col-lg-3 benefit-item mb-5 mb-lg-0" data-aos="fade-up" data-aos-once="true"
				data-aos-delay="600" data-aos-duration="600" onmouseover="changeImageOutline(this)"
				onmouseout="changeImageFilled(this)" data-benefit="1">
				<div class="p-4 bg-white h-100">
					<img src="<?= base_url(); ?>assets/img/new/salary-outline.png" alt="Vector" class="mb-4 filter-blue">
					<p class="font-weight-bold text-blue mb-2">Deviden Bulanan</p>
					<p class="text-grey">Deviden hingga 100%, balik modal kurang dari 6 bulan dan bergaransi.</p>
				</div>
			</div>
			<div class="col-12 col-md-6 col-lg-3 benefit-item mb-5 mb-lg-0" data-aos="fade-up" data-aos-once="true"
				data-aos-delay="900" data-aos-duration="600" onmouseover="changeImageOutline(this)"
				onmouseout="changeImageFilled(this)" data-benefit="2">
				<div class="p-4 bg-white h-100">
					<img src="<?= base_url(); ?>assets/img/new/halal-outline.png" alt="Vector" class="mb-4 filter-blue">
					<p class="font-weight-bold text-blue mb-2">Halal</p>
					<p class="text-grey">Lorem ipsum dolor sit amet consectetur adipisicing elit. Unde sunt in
						recusandae temporibus.</p>
				</div>
			</div>
			<div class="col-12 col-md-6 col-lg-3 benefit-item mb-5 mb-lg-0" data-aos="fade-up" data-aos-once="true"
				data-aos-delay="1200" data-aos-duration="600" onmouseover="changeImageOutline(this)"
				onmouseout="changeImageFilled(this)" data-benefit="3">
				<div class="p-4 bg-white h-100">
					<img src="<?= base_url(); ?>assets/img/new/thumbs-up-outline.png" alt="Vector" class="mb-4 filter-blue">
					<p class="font-weight-bold text-blue mb-2">Mulai Dari Rp 50.000</p>
					<p class="text-grey">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Architecto, maiores.
					</p>
				</div>
			</div>
			<div class="col-12 col-md-6 col-lg-3 benefit-item mb-5 mb-lg-0" data-aos="fade-up" data-aos-once="true"
				data-aos-delay="1500" data-aos-duration="600" onmouseover="changeImageOutline(this)"
				onmouseout="changeImageFilled(this)" data-benefit="4">
				<div class="p-4 bg-white h-100">
					<img src="<?= base_url(); ?>assets/img/new/badge-outline.png" alt="Vector" class="mb-4 filter-blue">
					<p class="font-weight-bold text-blue mb-2">Bisnis Unggulan</p>
					<p class="text-grey">Lorem ipsum dolor sit amet consectetur adipisicing elit. Sapiente, inventore?
					</p>
				</div>
			</div>
		</div>
	</div>
</section>


<section class="how-to">
	<div class="container">
		<div class="row">
			<div class="col-md-5" data-aos="fade-up" data-aos-once="true" data-aos-duration="600">
				<figure class="img-wrapper w-100">
					<img src="<?= base_url(); ?>assets/img/new/photo-1554672408-730436b60dde.jpg"
						alt="Beragma Fitur yang Memudahkanmu Berinvestasi" class="img-fluid">
				</figure>
			</div>
			<div class="col-md-7 my-auto">
				<h2 class="text-left mb-5" data-aos="fade-up" data-aos-once="true"
					data-aos-delay="300" data-aos-duration="600">Beragam Fitur yang <br class="d-none d-md-block">
					Memudahkanmu Berinvestasi</h2>
				<ul class="list-features">
					<li class="d-flex align-items-center mb-4" data-aos="fade-up" data-aos-once="true"
						data-aos-delay="600" data-aos-duration="600">
						<div class="number-wrapper">
							<div class="number mr-3 d-flex justify-content-center align-content-center text-center">
								1
							</div>
						</div>
						<p class="text-capitalize mb-0">Verifikasi Akun Instant Kurang dari 20 Detik</p>
					</li>
					<li class="d-flex align-items-center mb-4" data-aos="fade-up" data-aos-once="true"
						data-aos-delay="900" data-aos-duration="600">
						<div class="number-wrapper">
							<div class="number mr-3 d-flex justify-content-center align-content-center text-center">
								2
							</div>
						</div>
						<p class="text-capitalize mb-0">E-RUPS (Rapat Umum Pemegang Saham/Sukuk Elektronik)</p>
					</li>
					<li class="d-flex align-items-center mb-4" data-aos="fade-up" data-aos-once="true"
						data-aos-delay="1200" data-aos-duration="600">
						<div class="number-wrapper">
							<div class="number mr-3 d-flex justify-content-center align-content-center text-center">
								3
							</div>
						</div>
						<p class="text-capitalize mb-0">E-Votting (Pengambilan Keputusan Usaha Secara Elektronik)
						</p>
					</li>
					<li class="d-flex align-items-center mb-4" data-aos="fade-up" data-aos-once="true"
						data-aos-delay="1500" data-aos-duration="600">
						<div class="number-wrapper">
							<div class="number mr-3 d-flex justify-content-center align-content-center text-center">
								4
							</div>
						</div>
						<p class="text-capitalize mb-0">Laporan Bulanan Real Time
						</p>
					</li>
					<li class="d-flex align-items-center mb-4" data-aos="fade-up" data-aos-once="true"
						data-aos-delay="1800" data-aos-duration="600">
						<div class="number-wrapper">
							<div class="number mr-3 d-flex justify-content-center align-content-center text-center">
								5
							</div>
						</div>
						<p class="text-capitalize mb-0">Transparansi
						</p>
					</li>
				</ul>
			</div>
		</div>
	</div>
</section>

<section class="projects">
	<div class="container">
		<div class="row mb-5">
			<div class="col-12 col-md-8">
				<h2 class="text-left font-weight-bold">Daftar Project</h2>
				<p class="text-grey text-left">Lihat daftar investasi bisnis yang sedang berlangsung dan temukan peluang untuk berinvestasi hari ini.</p>
			</div>
			<div class="col-12 col-md-4 text-lg-right">
				<a href="#" class="custom_btn-blue">All Projects</a>
			</div>
		</div>
		<div class="row project-list mx-0">
			<?php
				$datany['data_produk'] = $data_produk;
            	$this->load->view("list-data", $datany);
            ?>
		</div>
	</div>
</section>

<section class="partners">
	<div class="container">
		<h2 class="text-center mb-4">Didukung Oleh</h2>
		<div class="row">
			<div class="col-md-8 mx-auto">
				<div class="row partner-list justify-content-center">
					<div class="col-4 d-flex justify-content-center align-items-center">
						<img src="<?= base_url(); ?>assets/img/partner/logo_ksei.png" alt="PT Kustodian Sentral Efek Indonesia"
							class="img-fluid">
					</div>
					<div class="col-4 d-flex justify-content-center align-items-center">
						<img src="<?= base_url(); ?>assets/img/partner/logo_pse.png" alt="PSE Kominfo" class="img-fluid">
					</div>
					<div class="col-4 d-flex justify-content-center align-items-center">
						<img src="<?= base_url(); ?>assets/img/partner/logo_bsi.png" alt="Bank Syariah Indonesia"
							class="img-fluid">
					</div>
					<div class="col-4 d-flex justify-content-center align-items-center">
						<img src="<?= base_url(); ?>assets/img/partner/logo_mui.png" alt="Majelis Ulama Indonesia"
							class="img-fluid">
					</div>
				</div>
			</div>
		</div>
	</div>
</section>

<section class="testimonial">
	<div class="container">
		<h2 class="text-left">Apa Kata Mereka?</h2>
		<p class= text-grey mb-5">Lorem ipsum dolor sit amet consectetur, adipisicing elit.
			Minima
			ratione,
			velit culpa obcaecati,
			consectetur ab ad assumenda libero quaerat ipsa placeat aperiam repellendus mollitia distinctio saepe
			dolor. Cum, nobis enim?</p>
		<div class="row">
			<div class="col-md-4 testimonial-item mb-5 mb-lg-0">
				<div class="card border">
					<figure class="img-wrapper m-0 text-center mb-2">
						<img src="<?= base_url(); ?>assets/img/new/avatar.jpg" alt="Avatar" class="avatar" width="70"
							height="70">
					</figure>
					<h5 class="text-center testimonial-name mb-2">Hugo Adams</h5>
					<span class="text-center d-block testimonial-job mb-3">Investor</span>
					<p class="text-center">Lorem ipsum dolor sit amet consectetur adipisicing elit. Excepturi
						aliquid distinctio fuga
						amet eos sed.</p>
				</div>
			</div>
			<div class="col-md-4 testimonial-item mb-5 mb-lg-0">
				<div class="card border">
					<figure class="img-wrapper m-0 text-center mb-2">
						<img src="<?= base_url(); ?>assets/img/new/avatar.jpg" alt="Avatar" class="avatar" width="70"
							height="70">
					</figure>
					<h5 class="text-center testimonial-name mb-2">Hugo Adams</h5>
					<span class="text-center d-block testimonial-job mb-3">Investor</span>
					<p class="text-center">Lorem ipsum dolor sit amet consectetur adipisicing elit. Excepturi
						aliquid distinctio fuga
						amet eos sed.</p>
				</div>
			</div>
			<div class="col-md-4 testimonial-item mb-5 mb-lg-0">
				<div class="card border">
					<figure class="img-wrapper m-0 text-center mb-2">
						<img src="<?= base_url(); ?>assets/img/new/avatar.jpg" alt="Avatar" class="avatar" width="70"
							height="70">
					</figure>
					<h5 class="text-center testimonial-name mb-2">Hugo Adams</h5>
					<span class="text-center d-block testimonial-job mb-3">Investor</span>
					<p class="text-center">Lorem ipsum dolor sit amet consectetur adipisicing elit. Excepturi
						aliquid distinctio fuga
						amet eos sed.</p>
				</div>
			</div>
		</div>
	</div>
</section>
<?php

?>
<script type="text/javascript">
	function changeImageOutline(element) {
		if (element.getAttribute('data-benefit') == 1) {
			element
			.getElementsByTagName('img')[0]
			.setAttribute('src', '<?= base_url(); ?>assets/img/new/salary.png');
			element.getElementsByTagName('img')[0].classList.remove('filter-blue');
		}
		if (element.getAttribute('data-benefit') == 2) {
			element
			.getElementsByTagName('img')[0]
			.setAttribute('src', '<?= base_url(); ?>assets/img/new/halal.png');
			element.getElementsByTagName('img')[0].classList.remove('filter-blue');
		}
		if (element.getAttribute('data-benefit') == 3) {
			element
			.getElementsByTagName('img')[0]
			.setAttribute('src', '<?= base_url(); ?>assets/img/new/thumbs-up.png');
			element.getElementsByTagName('img')[0].classList.remove('filter-blue');
		}
		if (element.getAttribute('data-benefit') == 4) {
			element
			.getElementsByTagName('img')[0]
			.setAttribute('src', '<?= base_url(); ?>assets/img/new/badge.png');
			element.getElementsByTagName('img')[0].classList.remove('filter-blue');
		}
	}

	function changeImageFilled(element) {
		if (element.getAttribute('data-benefit') == 1) {
			element
			.getElementsByTagName('img')[0]
			.setAttribute('src', '<?= base_url(); ?>assets/img/new/salary-outline.png');
			element.getElementsByTagName('img')[0].classList.add('filter-blue');
		}
		if (element.getAttribute('data-benefit') == 2) {
			element
			.getElementsByTagName('img')[0]
			.setAttribute('src', '<?= base_url(); ?>assets/img/new/halal-outline.png');
			element.getElementsByTagName('img')[0].classList.add('filter-blue');
		}
		if (element.getAttribute('data-benefit') == 3) {
			element
			.getElementsByTagName('img')[0]
			.setAttribute('src', '<?= base_url(); ?>assets/img/new/thumbs-up-outline.png');
			element.getElementsByTagName('img')[0].classList.add('filter-blue');
		}
		if (element.getAttribute('data-benefit') == 4) {
			element
			.getElementsByTagName('img')[0]
			.setAttribute('src', '<?= base_url(); ?>assets/img/new/badge-outline.png');
			element.getElementsByTagName('img')[0].classList.add('filter-blue');
		}
		}
	
		if(sessionStorage.getItem("partner_tx_id")){
		if(sessionStorage.getItem("partner_tx_id") != ''){
        	var trx = sessionStorage.getItem("partner_tx_id");
        	var settings = {
			  "url": "https://api-stg.oyindonesia.com/api/payment-checkout/status?partner_tx_id="+trx+"&send_callback=false",
			  "method": "GET",
			  "timeout": 0,
			  "headers": {
			    "x-oy-username": "pendanaid",
			    "x-api-key": "d4223670-1abb-491c-be03-c32370774324",
			    "content-type": "application/json"
			  },
			};

			$.ajax(settings).done(function (response) {
			  console.log(response);
			  // sessionStorage.setItem("partner_tx_id", "");
			  data = {
		        amount:response.data.amount,
		        sender_name:response.data.sender_name,
		        status:response.data.status,
		        email:response.data.email,
		      }
		      console.log(data);
		      if(response.data.status=="complete"){
		      $.ajax({
			      method: "POST",
			      url: "<?php echo base_url('investor/saveOy'); ?>",
			      data: data 
			      
			    })
		      	sessionStorage.setItem("partner_tx_id", "");
		  		}else{
		  			console.log('not set yet');
		  		}
			});
    	}
    }

	$(document).ready(function(){
		$(".rf").change(function(){
			filternya();
		});
	});
	function filternya(){ 
		var n=0;
		var nilai = {};
		var fi=["kampanye","tenor","bunga","urutan"];
		$(".rf:checked").each(function(){
			var tv = $(this).val();
			nilai[fi[n]]=tv;
			//console.log("val"+n+"->"+tv);
			n++;
		});
		console.log(nilai);
		$.ajax({
			url: "<?php echo base_url(); ?>invest/indexfilter", 
			data : nilai,
			type:"post",
			dataType:"html",
			success: function(result){ 
				$("#list-data").html(result);
			}
		});
	}
</script>